import { Card, CardContent, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { TopicCardProps } from "@/types/topic.types";
import { DynamicIcon } from 'lucide-react/dynamic';
import SentimentChart from "./SentimentChart";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle,
  DialogDescription, DialogTrigger, DialogClose
} from "@/components/ui/dialog";

export default function TopicCard({ topic } : TopicCardProps) {
    
    const chartData = [
        { name: "positive", value: topic.sentiment_values.average_pos },
        { name: "neutral", value: topic.sentiment_values.average_neu },
        { name: "negative", value: topic.sentiment_values.average_neg },
    ];

    const c = topic.sentiment_values.average_compound
    
    const smileyIcon =
    c >= 0.05
        ? "smile"
        : c <= -0.05
        ? "frown"
        : "meh"
    const compoundDisplayText =
    c >= 0.05
        ? "positive"
        : c <= -0.05
        ? "negative"
        : "neutral"

    return(
        <Card>
            <CardHeader className="flex gap-4 justify-between space-y-0 pb-2">
                <CardTitle className="text-lg pt-1">
                    {topic.label}
                </CardTitle>
                <div className="flex flex-col items-center">
                    <DynamicIcon name={smileyIcon}/>
                    <span className="text-xs text-gray-500 mt-1">
                        {topic.sentiment_values.average_compound}
                    </span>
                    <span className="text-xs text-gray-500">
                        {compoundDisplayText}
                    </span>
                </div>
            </CardHeader>
            <CardContent className="text-sm">
                {topic.summary && (
                <div className="mb-4">
                    <p className="text-sm text-muted-foreground leading-snug line-clamp-3 hyphens-auto">
                    {topic.summary}
                    </p>

                    <Dialog>
                    <DialogTrigger asChild>
                        <button className="text-xs underline text-muted-foreground mt-1 hover:no-underline">
                        Read full summary
                        </button>
                    </DialogTrigger>

                    <DialogContent className="sm:max-w-lg">
                        <DialogHeader>
                        <DialogTitle>{topic.label}</DialogTitle>
                        <DialogDescription>Summary generated by an AI model</DialogDescription>
                        </DialogHeader>

                        <div className="text-sm whitespace-pre-wrap">
                        {topic.summary}
                        </div>

                        <div className="mt-2 text-[10px] text-muted-foreground">
                        AI-generated summary · may contain inaccuracies
                        </div>
                    </DialogContent>
                    </Dialog>
                </div>
                )}
                <SentimentChart data={chartData}/>
            </CardContent>
            <CardFooter className="flex items-center gap-4 justify-between space-y-0 pb-2">
                <div className="text-xs text-gray-500">
                    {topic.num_posts} posts • {topic.sentiment_values.comment_count} comments
                </div>
            </CardFooter>
        </Card>
        
    )
}